### ISSUE TITLE
Regeln

### ISSUE THREAD

**Issue by criztovyl** [atiw-sportfest/datenbank#1]
- [x] Regel Index
- [x] ~Flag für Regeln, die erst am Ende ausgewertet werden~
- [x] Ergebnis Tabelle zu Variable umbenennen (Prozeduren anpassen)
- [x] ~Ist Hauptvariable in Tabelle einfügen~

**Comment by joham97** [comment]
- [ ] Ergebnis Tabelle zu Variable umbenennen (Prozeduren anpassen)

- [ ] Ist Hauptvariable in Tabelle einfügen
